version: '3.8'

services:
  postgres:
    ports:
      - '5432:5432'
    restart: unless-stopped
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: game-api
      POSTGRES_USER: kwong2000
      POSTGRES_PASSWORD: 1234abcd
    container_name: postgres-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      retries: 5
      timeout: 5s
      interval: 10s
      test: ['CMD-SHELL', 'pg_isready -U kwong2000 -d game-api']

  redis:
    ports:
      - '6379:6379'
    restart: unless-stopped
    image: redis:8.6-alpine
    container_name: redis-cache
    volumes:
      - redis_data:/data
    healthcheck:
      retries: 5
      timeout: 5s
      interval: 10s
      test: ['CMD', 'redis-cli', 'ping']

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
